### ISSUE TITLE
Enemy - NormalEnemyFacory

### ISSUE THREAD

**Issue by frankzhongzd** [CSC207-2022F-UofT/course-project-eldendisk#11]
Create normal-type enemies

**Responsibility**
Set enemy's type to "Normal"
Set the enemyStat to 70% of the player's current stats
Set enemy's available moves(4 moves)

**Comment by frankzhongzd** [comment]
Enemy's moves' attack damage number is calculated and assigned through the CalculateDMG interface

**Comment by DongminC7** [comment]
Enemy's set of moves should consist of four randomly selected moves from the set of moves
